name: Docker Build CI

# Should run on pushes to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download code from Github repository
      uses: actions/checkout@v4

    - name: Try to build Docker image
      run: |
        docker build -t test-provera:latest ./application
        echo "Docker image successfully built!"

    - name: Verify Docker Compose
      run: |
        docker compose -f ./application/docker-compose.yaml config
        echo "Docker Compose file is valid!"